### ISSUE TITLE
Exception : Error validating access token

### ISSUE THREAD

**Issue by urbanistica** [mmangino/mogli#10]
Not sure how I got to this state: things were working, then all I recall doing is adding a js command "FB.logout()" to my logout button. Since then, my app crashes with :

Exception (OAuthException: Error validating access token.):
    /home/slugs/170027_799d077_f9ad/mnt/.gems/gems/mogli-0.0.14/lib/mogli/client.rb:136:in `raise_error_if_necessary'
    /home/slugs/170027_799d077_f9ad/mnt/.gems/gems/mogli-0.0.14/lib/mogli/client.rb:78:in`map_data'
    /home/slugs/170027_799d077_f9ad/mnt/.gems/gems/mogli-0.0.14/lib/mogli/client.rb:69:in `get_and_map'
    /home/slugs/170027_799d077_f9ad/mnt/.gems/gems/mogli-0.0.14/lib/mogli/model.rb:108:in`find'
    /home/slugs/170027_799d077_f9ad/mnt/.gems/gems/mogli-0.0.14/lib/mogli/model.rb:98:in `fetch'
    /app/controllers/application.rb:95:in`parseStandardParams'

The line being called is in this : @fb_user = current_facebook_user.fetch 

found here :

begin
       if ! current_facebook_user.nil?
         @fb_user = current_facebook_user.fetch 
         update_logins
       else
         if session[:fb_login] == true
           session[:user_id] = nil
         end
       end
    rescue

the rescue block doesn't see to help anything… what am I doing wrong? How can I test the validity of a call like  current_facebook_user.fetch, which seems to be the problem?

**Comment by mmangino** [comment]
rescue should work now. I was raising an Exception which doesn't get caught by the default rescue block. It sounds like you need to log back in because the token is invalid.
