### ISSUE TITLE
problem with 0.0.15

### ISSUE THREAD

**Issue by renaud** [mmangino/mogli#11]
first, thanks for sharing your code.

I've had a problem with the latest 0.0.15:

```
./mogli.rb:9: uninitialized constant Client (NameError)
from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
```

works fine with 0.0.14:
    require "rubygems"
    gem 'mogli', '=0.0.14'
    require "mogli"

```
client = Mogli::Client.new("foo")   
myself  = Mogli::User.find("me",client)
puts myself
```

let me know if I'm doing something wrong...

**Comment by mmangino** [comment]
I can't duplicate this. It's working fine for me.

**Comment by renaud** [comment]
ok. i tried with Ubuntu & Mac... probably because of my settings...
