### ISSUE TITLE
undefined method `has_key' for #<Hash> in lib/mogli/client.rb:214:in `determine_class'

### ISSUE THREAD

**Issue by ckbhodge** [mmangino/mogli#114]
I'm getting this error in my oauth controller using the latest code ( my gemfile has this line: gem "mogli", :git => 'git://github.com/mmangino/mogli.git' ).  I wasn't getting it with the version from rubygems.org.

NoMethodError in OauthController#index 

/lib/mogli/client.rb:214:in `determine_class'
/lib/mogli/client.rb:198:in`create_instance'
/lib/mogli/client.rb:193:in `map_to_class'
/lib/mogli/client.rb:153:in`map_data'
/lib/mogli/client.rb:142:in `get_and_map'
/lib/mogli/model.rb:155:in`find'
app/controllers/oauth_controller.rb:24:in `index'

The method index is below:

  def index
    redirect_to new_oauth_path and return unless session[:at]
    puts session[:at]
    user = Mogli::User.find("me",Mogli::Client.new(session[:at]))
    @user = user
    puts "in oauth_controller:index, @user = " + @user.to_s
    redirect_to next_path
  end

**Comment by mmangino** [comment]
Can you dump the response from Facebook to see what it looks like? Also, are you on a recent version of HTTParty? They have a fix that will hopefully take care of some of the issues.

Mike

**Comment by ckbhodge** [comment]
Hi Mike, thanks for the followup.

Unfortunately, I think we're stuck with httparty 0.7.8 as we have a
dependency on it (one of our devs is running on windows):

Bundler could not find compatible versions for gem "httparty":
  In Gemfile:
    httparty (~> 0.7.8) x86-mingw32

```
httparty (0.8.3)
```

How would you like me to dump the response from Facebook?  The session[:at]
parameter looks like a well-formed auth token.

By the way, I am unblocked as I changed my mogli gem to point to my github
branch of mogli with the change that I need but prior to this conflict.

Thanks!
Colin

On Tue, May 1, 2012 at 5:58 AM, Mike Mangino <
reply@reply.github.com

**Comment by mmangino** [comment]
I don't think it's the session, I think it's the response from Facebook in the find. I would love to see the raw body as well as the http response code.

Mike

**Comment by thomaspouncy** [comment]
As far as I can tell the original issue posted here was just a typo in the code. At line 214 of client.rb there is a "has_key" that should be "has_key?". My forked repo seems to be a bit messed up otherwise I would just fork and fix this...

**Comment by ckbhodge** [comment]
Mike - is there an easy way to access the raw body and http response code?

**Comment by mmangino** [comment]
Where are you trying to access it from? The response is just a HTTParty response. so you have access to whatever they provide.

Mike

**Comment by mmangino** [comment]
I just pushed a fix for this

**Comment by mmangino** [comment]
And now I'm closing

**Comment by ckbhodge** [comment]
Thanks - seems to have fixed it!
