### ISSUE TITLE
MultiJson::DecodeError: 743: unexpected token at 'false' 

### ISSUE THREAD

**Issue by joerixaop** [mmangino/mogli#115]
Ruby version 1.9.3

```
irb(main):004:0> Mogli::Post.find("some post id that's apparently not accessible", client)
MultiJson::DecodeError: 743: unexpected token at 'false'
        from /Users/joeri/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/json/common.rb:148:in `parse'
        from /Users/joeri/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/json/common.rb:148:in `parse'
        from /Users/joeri/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/multi_json-1.0.4/lib/multi_json/engines/json_common.rb:9:in `decode'
        from /Users/joeri/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/multi_json-1.0.4/lib/multi_json.rb:76:in `decode'
        from /Users/joeri/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/httparty-0.8.3/lib/httparty/parser.rb:119:in `json'
        ....
```

This is using MultiJson 1.0.4, but without using any JSON specific gems (i.e. using the standard library json implementation).

Incidentally MultiJson has many newer versions than 1.0.4 but it seems that the Mogli insists on ~> 1.0.3 (using MultiJson 1.3.5 doesn't help really in this case though). This makes it difficult to use in new projects, since other gems do insist on more recent MultiJson versions.

**Comment by mmangino** [comment]
Does the most recent version from Github fix this? I'm happy to take patches to move to newer versions of MultiJSON/.

Mike

**Comment by joerixaop** [comment]
Yes, still happens when using a git version of mogli. The problem is in the JSON parser (or rather the problem is the facebook response, `false` is not valid JSON), so I'm wondering what JSON parser other people are using.

**Comment by mmangino** [comment]
We could just do a string comparison and do that one mapping manually.
