### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by gtd** [mmangino/mogli#118]
Having one would be extremely useful for upgrades which terrify me a bit when it comes to Facebook.

**Comment by mmangino** [comment]
The git log is your best changelog. Just look at the commit messages. That's always up to date.

**Comment by gtd** [comment]
I disagree strongly with this on a philosophical level.  A curated changelog is a tremendously useful tool for the majority of the user base who are not knee-deep in the code and may have quite a long span of versions to go through.  This is quite painful to do on github and requires a clone to run git-log for long histories.  Aside from that not every contributor follows best practices for git commit messages, so you might miss some good information, or there might be major refactorings that add noise to the git log.

Anyway, thats just my opinion and it's your project.  However, if you do plan on using only git commit messages can I make a secondary request that you include version numbers in the gemspec bump commits?

**Comment by mmangino** [comment]
Okay, if this is something you feel strongly about, I'll get it a try. I'll export the log and clean it up a bit to start with and then I'll try to keep it up going forward.

Mike

**Comment by gtd** [comment]
Thanks Mike!  I really have appreciated your work over the years.  Been maintaining a FB app since 2007 and was very pleased when you took up Facebooker and we could finally get off rfacebook.  Those were dark days.

**Comment by gtd** [comment]
I'm set for another Mogli update and it's really hard to see what's changed.  Even if the git log had the version numbers in the commit message instead of requiring looking at the diff that would be an improvement.

**Comment by mmangino** [comment]
I appreciate what you're saying, but for me the amount of effort to keep that up is more than I am willing to spend. If you want to know what changes, you can look at this view: https://github.com/mmangino/mogli/commits/master 

I always mark version changes with the same commit method.

**Comment by gtd** [comment]
Clearly I'm aware of how to use git log.  I thought changelog/history was standard practice for all open source, but if you're set in your workflows there's nothing more for me to say, except perhaps to suggest that you delete the changelog for tidiness sake.
