### ISSUE TITLE
Data for Mogli::Address is sometimes not a hash

### ISSUE THREAD

**Issue by yitaosun** [mmangino/mogli#126]
Mogli::Place.find("552728771407219", client) would throw at gems/mogli-0.0.43/lib/mogli/model.rb:22

The data, taken from Graph API Explorer, looks like

``` ruby
{
  "id": "552728771407219", 
  ...
  "location": "Room18 Taipei", 
  ...
}
```

**Comment by yitaosun** [comment]
My quick fix was to add location to define_properties and comment out hash_populating_accessor :location, "Address".  It's okay for me since I'm not really interested in the location object, but this probably wouldn't work for others.

``` ruby
define_properties :id, :name, :category, :username, :can_post, :phone, :website, :checkins, :link, :public_transit, :likes, :picture, :location
# hash_populating_accessor :location, "Address"
```

**Comment by mmangino** [comment]
Yuck. I'm not sure how to fix this. I guess we could allow location to be either an object or a string, but that's nasty. Or maybe allow a hash populating accessor to specify a default field to be populated in the case of a string. That's probably better.

Do you have any interest in trying that patch or do you want me to add it to my list?
