### ISSUE TITLE
Get extended page access tokem

### ISSUE THREAD

**Issue by nishant-n** [mmangino/mogli#133]
Hello mmangino,

I need your help, if possible please let me know how I can call Authenticator.new.authorize_url method in order to achieve http://stackoverflow.com/questions/10183625/extending-facebook-page-access-token 

Thanks you very much for any help.

**Comment by mmangino** [comment]
I don't use this functionality, so I have no idea how or if it works.

Mike

**Comment by nishant-n** [comment]
I have done by :

@authenticator ||= Mogli::Authenticator.new(app_config['app_id'],app_config['secret'], url)
new_token = @authenticator.extend_access_token(token)
client = Mogli::Client.new(new_token)
Now this client have long lived token. 

Thank you
