### ISSUE TITLE
No method error!

### ISSUE THREAD

**Issue by nishant-n** [mmangino/mogli#134]
Hello I'm using mogile version is mogli ( 0.0.11) and getting following error.

NoMethodError: undefined method `extend_access_token' for #Mogli::Authenticator:0xb466418

Please help me on this.

**Comment by mmangino** [comment]
I'm not sure what you expect. You're trying to call a method that doesn't exist. Why do you think this should exist? Have you looked at the code and tried to find the problem?

**Comment by nishant-n** [comment]
Thanks for update, I found the solution that is issue fixed in later version on Mogli.
