### ISSUE TITLE
Failing to check permission exist or not

### ISSUE THREAD

**Issue by sosuren** [mmangino/mogli#152]
I tried to check if the user has granted `:publish_action` permission or not. Just with simple line below:

```
client = Mogli::Client.new("access-token-here")
myself = Mogli::User.find("me", client)
myself.has_permission?(:publish_actions)
```

But it failed with below trace: 

```
NoMethodError: undefined method `first' for nil:NilClass
from /.../.rvm/gems/ruby-2.1.2@bob/bundler/gems/mogli-5e209a446e06/lib/mogli/user.rb:131:in `fetch_permissions'`
```

I went through the code and saw usage of `permissions` table in [https://github.com/mmangino/mogli/blob/master/lib/mogli/user.rb#L127](here) 
But this table do not exist in my database. Do I suppose to run some rake task?

Any help will be very much appreciated. Thanks

**Comment by mmangino** [comment]
Hello,

This code hasn't been updated in years. I would imagine that Facebook has made breaking changes since then. I would be surprised if any of this works.

**Comment by sosuren** [comment]
I was just fixing an old ruby project rails 3.2.19 and it used this library. 
Thank you very much
