### ISSUE TITLE
Problem mapping user location

### ISSUE THREAD

**Issue by karanmg** [mmangino/mogli#16]
In a project that uses facebooker2, I'm trying to get the user's location. 
I'm using 
    m_location = get_and_map(current_facebook_user.id, Mogli::Profile, { :fields => "location" })
however, which always fails to map to the Mogli::Profile class, with messages: 
    Warning: property name doesn't exist for class Mogli::Location
    Warning: property id doesn't exist for class Mogli::Location
The URL being accessed is:
    https://graph.facebook.com/10002252.....?fields=location&access_token=154929
which returns
    {
       "id": "10002252.....",
       "location": {
             "id": "114952118516947",
             "name": "San Francisco, California"
         }
    }
Looking through Mogli code, to discover where Mogli:Location is getting picked up, since I'm specifying Mogli::Profile, I see in client.rb:
    def create_instance(klass,data)
      klass_to_create =  determine_class(klass,data)
      if klass_to_create.nil?
          raise UnrecognizeableClassError.new("unable to recognize klass for #{klass.inspect} => #{data.inspect}")
      end
      klass_to_create.new(data,self)
    end

```
def determine_class(klass_or_klasses,data)
  return constantize_string(data['type']) if data.key?('type') && klass_or_klasses == Mogli::Model
  klasses = Array(klass_or_klasses).map { |k| constantize_string(k)}
  klasses.detect {|klass| klass.recognize?(data)} || klasses.first
end
```

where klass_or_klasses will be "location" and so automatically Mogli::Location will be initialized, and will fail to map because it does not have :id, :name as accessors (they are in class Profile, Location inherits from Model).

Am I missing something here? Is there another way to get the user's location data?

Thanks

**Comment by mmangino** [comment]
You should need to do that much work. You can just call "current_facebook_user.fetch"

**Comment by karanmg** [comment]
Yes, I do that - it populates profile properties of the user (first_name, etc), but current_facebook_user.location.nil? is always true
