### ISSUE TITLE
Exception: OAuthException: Invalid OAuth access token on myself  = Mogli::User.find("me",client)

### ISSUE THREAD

**Issue by divyaiyer** [mmangino/mogli#18]
I have followd your README and when I tried you sample code on console I am getting this error.
Here client = Mogli::Client.new("your_access_token") what is this 'your_access_token' and from where can I get it?

Thanks
Divya

**Comment by mmangino** [comment]
It should come from Facebook. My example code on github shows a running app. If you have other questions, you can ask them on the Facebooker google group
