### ISSUE TITLE
undefined method 'split' called on HTTParty::Response

### ISSUE THREAD

**Issue by raghums** [mmangino/mogli#2]
# I am trying to use the graph api for getting the access_token given a code, I get the following error.

NoMethodError (private method `split' called for #<HTTParty::Response:0x1031bfa40>):
  httparty (0.6.1) lib/httparty/response.rb:59:in`method_missing'
#   mogli (0.0.14) lib/mogli/client.rb:37:in `create_from_code_and_authenticator'

Not sure if this is actually an issue, since the invocation passes without issues sometimes (without throwing an error). By the looks of the error, it seemed like a missing condition check on the response object (before invoking split). I am not too aware of HTTParty to dig any deeper.

-raghu

**Comment by mmangino** [comment]
That seems like an odd error. I've never run into it. Does it fix things if you call .body on the response before splitting it?

**Comment by raghums** [comment]
Here is a reproduction of the issue (using irb)

> > require 'mogli'
> > => true
> > authenticator=Mogli::Authenticator.new("dummy", "dummy", "dummy")
> > => #<Mogli::Authenticator:0x101530de8 @callback_url="dummy", @secret="dummy", @client_id="dummy">
> > client = Mogli::Client.create_from_code_and_authenticator("dummy", authenticator)
> > Called url https://graph.facebook.com/oauth/access_token?client_id=dummy&redirect_uri=dummy&client_secret=dummy&code=dummy and Got response #<HTTParty::Response:0x101525600 @parsed_response={"error"=>{"type"=>"OAuthException", "message"=>"redirect_uri isn't an absolute URI. Check RFC 3986."}}, @response=#<Net::HTTPBadRequest 400 Bad Request readbody=true>, @headers={"expires"=>["Sat, 01 Jan 2000 00:00:00 GMT"], "p3p"=>["CP=\"DSP LAW\""], "content-type"=>["text/javascript; charset=UTF-8"], "connection"=>["close"], "www-authenticate"=>["OAuth \"Facebook Platform\" \"invalid_request\" \"redirect_uri isn't an absolute URI. Check RFC 3986.\""], "date"=>["Tue, 05 Oct 2010 13:38:38 GMT"], "content-length"=>["99"], "set-cookie"=>["datr=1286285918-f09b711628c04afc60944ac6fce340da196c633cfc0b86410902d; expires=Thu, 04-Oct-2012 13:38:38 GMT; path=/; domain=.facebook.com"], "cache-control"=>["no-store"], "pragma"=>["no-cache"]}>
> > NoMethodError: private method `split' called for #<HTTParty::Response:0x101526af0>
> >     from /Library/Ruby/Gems/1.8/gems/httparty-0.6.1/lib/httparty/response.rb:59:in`method_missing'
> >     from /Library/Ruby/Gems/1.8/gems/mogli-0.0.14/lib/mogli/client.rb:38:in `create_from_code_and_authenticator'
> >     from (irb):3

There is no exception thrown when .body is invoked before split. But I am not sure if it would work in the happy case (It is a little hard for me test that scenario as I would need a valid 'code' from facebook)

Here is the response with .body invoked before split:

Called url https://graph.facebook.com/oauth/access_token?client_id=dummy&redirect_uri=dummy&client_secret=dummy&code=dummy and Got response #<HTTParty::Response:0x1015255d8 @parsed_response={"error"=>{"type"=>"OAuthException", "message"=>"redirect_uri isn't an absolute URI. Check RFC 3986."}}, @response=#<Net::HTTPBadRequest 400 Bad Request readbody=true>, @headers={"expires"=>["Sat, 01 Jan 2000 00:00:00 GMT"], "p3p"=>["CP=\"DSP LAW\""], "content-type"=>["text/javascript; charset=UTF-8"], "connection"=>["close"], "www-authenticate"=>["OAuth \"Facebook Platform\" \"invalid_request\" \"redirect_uri isn't an absolute URI. Check RFC 3986.\""], "date"=>["Tue, 05 Oct 2010 13:41:59 GMT"], "content-length"=>["99"], "set-cookie"=>["datr=1286286119-a5824996a336d82ba3d25300c2e625dd732ee96e88b2c260554c2; expires=Thu, 04-Oct-2012 13:41:59 GMT; path=/; domain=.facebook.com"], "cache-control"=>["no-store"], "pragma"=>["no-cache"]}>
=> #<Mogli::Client:0x101524c78 @default_params={}, @expiration=Fri Oct 02 19:11:59 +0530 2020, @access_token=nil>

I think it would be better if Mogli could throw an appropriate exception in such cases instead of the client code having to deal with "NoMethodError" :)

**Comment by mmangino** [comment]
That would be awesome. Do you want to add the check for a successful status and raise an error otherwise? Then just send me a pull request.

**Comment by raghums** [comment]
Ok, I will do that. Please give me a couple of days time.

**Comment by raghums** [comment]
Issue 9 (http://github.com/mmangino/mogli/issues#issue/9) has the pull request for this issue.

**Comment by mmangino** [comment]
Thanks! I just merged this.
