### ISSUE TITLE
NoMethodError: private method `split' called for #<HTTParty::Response:0x7699860>  

### ISSUE THREAD

**Issue by drcapulet** [mmangino/mogli#26]
I've experienced this error across multiple platforms but it appears to happen when Facebook doesn't like the sent code and returns an error. However, the `self.response_is_error?` method returns true for `post_data.class == HTTParty::Response` but false for `post_data.is_a?(HTTParty::Response)` in production, but the opposite in tests. Using `post_data.class == HTTParty::Response` causes the specs to fail even though the code works in production. While I can tell no reason why one wouldn't work while the other would, but they do. It has phased me for the past few days.

**Comment by mmangino** [comment]
It's not something I've seen, but I'm happy to take a patch with tests if you can get the tests squared away.
