### ISSUE TITLE
Properties not defined for this Dash

### ISSUE THREAD

**Issue by ferdyh** [mmangino/mogli#35]
I get this error when using mogli:

```
The property 'hometown' is not defined for this Dash.
```

If i remove hometown from my facebook profile i get the next one

```
The property 'location' is not defined for this Dash.
```

**Comment by mmangino** [comment]
What version are you using? This works fine for me.

**Comment by ferdyh** [comment]
rails 3.0.3
mogli 0.0.22
facebooker2 0.0.7

**Comment by mmangino** [comment]
Can you provide the response JSON you're getting? I want to see if I can figure out what is happening.

**Comment by ferdyh** [comment]
What the... I just tried it again and now it works... Maybe glitch in the Graph API?!

**Comment by mmangino** [comment]
Quite possibly. It happens from time to time. Let me know if it pops up again.

**Comment by ferdyh** [comment]
Will do, thanks for the quick reply

**Comment by jaredonline** [comment]
I just had this issue.

facebooker2 0.0.7
rails 3.0.0
mogli 0.0.23

This is the offending line:
@user = Mogli::User.find(current_facebook_user.id,current_facebook_client)

I'm not sure how to get the JSON response though.

**Comment by trobrock** [comment]
I am getting the same problem, didn't get this locally, but now on my server its happening

**Comment by jaredonline** [comment]
I just updated to 0.0.24 and it fixed the issue (probably because the newer version removed the Hashie dependencies).

There's a bug in the 0.0.24 release, but I have a pull request in for it: https://github.com/mmangino/mogli/pull/36

**Comment by trobrock** [comment]
After upgrading to 0.0.24 and trying to start server:

`gems/activesupport-2.3.10/lib/active_support/dependencies.rb:466:in`load_missing_constant': uninitialized constant Mogli::Hashie (NameError)`

**Comment by trobrock** [comment]
nm I applied that patch and it works

**Comment by jaredonline** [comment]
Either apply the commit from the pull request, or use my fork. 

Basically, in model/search.rb you need to take out the reference to Mogli::Hashie.

Change

module Search < Mogli::Hashie 

to 

module Search
