### ISSUE TITLE
uninitialized constant Mogli::Hashie

### ISSUE THREAD

**Issue by rlisowski** [mmangino/mogli#38]
Hi,
I use latest version of mogli 0.0.24 and get error
    ruby-1.9.2-p136/gems/mogli-0.0.24/lib/mogli/model/search.rb:2:in `module:Mogli': uninitialized constant Mogli::Hashie (NameError)
Your last commit repair that issue
    https://github.com/mmangino/mogli/commit/76a26c8221fbed36ef9014681b8e55c74e17c37d
Can You make a new version of gem?

regards

**Comment by mmangino** [comment]
You bet. 0.0.25 being released in the next few minute.

**Comment by rlisowski** [comment]
thanks
