### ISSUE TITLE
fetch_permissions error not caught

### ISSUE THREAD

**Issue by stevenou** [mmangino/mogli#42]
Past day I've been getting a bunch of errors when using has_permission?

I took a look and the FQL query in fetch_permissions is returning ["error_msg", "sms is not a member of the permissions table."]

It's breaking my whole site :( It seems like removing :sms from ALL_EXTENDED_PERMISSIONS fixes it, but I feel like there should be proper error handling instead of my ad-hoc solution.

Help? Thanks...

**Comment by mmangino** [comment]
You can remove that from the list of permissions it looks for. I'll try to release a new version shortly.

Mike

On Mar 16, 2011, at 5:33 AM, stevenou wrote:

> Past day I've been getting a bunch of errors when using has_permission?
> 
> I took a look and the FQL query in fetch_permissions is returning ["error_msg", "sms is not a member of the permissions table."]
> 
> It's breaking my whole site :(
> 
> Help? Thanks...
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mmangino/mogli/issues/42

## 

Mike Mangino
http://www.elevatedrails.com

**Comment by mmangino** [comment]
What would error handling look like? What would you expect the response to be from a failure of the call? It's easy to patch by just overriding the array, so I'm not sure how to make it better. 0.0.27 is released with a fix.

**Comment by stevenou** [comment]
I dunno :-| I'm more of a noob so I figured you would probably have a better solution. 

Either way, thanks for the new release :) As long as it works! And again, awesome job on the gem - I love it.
