### ISSUE TITLE
Items retrieved via FQL are not created correctly

### ISSUE THREAD

**Issue by aselder** [mmangino/mogli#45]
If you do something like:

```
client.fql_query("SELECT eid, name FROM event WHERE eid IN (#{[182880348415052, 172962332756022].join(',')})")
```

you get a warning 

```
Warning: property eid doesn't exist for class Mogli::Event
Warning: property eid doesn't exist for class Mogli::Event
```

and the resulting Mogli::Event objects have nil id fields, which means that any further queries on those objects blowup. (Exception: No node specified)

It looks like this is caused by FQL and the Graph API specifying different keys (eid vs id in the case of events).

This seems to be a very general problem, across many of the types (gender vs. sex in the User object)

**Comment by mmangino** [comment]
I would be happy to take a patch that implements and fql_mapping hash for each class. So in the event code, you could say fql_mapping :eid=>:id, :gender=>:sex and whatever else to help map the params.

**Comment by mmangino** [comment]
I'm closing this, but it's on my radar to work on this week.
