### ISSUE TITLE
Creating test users

### ISSUE THREAD

**Issue by zakmandhro** [mmangino/mogli#48]
Trying to create Facebook test users per http://developers.facebook.com/docs/test_users/. I couldn't figure out how to do this with Mogli/Facebooker:

```
client.post("/#{Facebooker2.app_id}/accounts/test-users", nil, :installed=>true, :permissions=>'read_stream')
```

Got:

```
Mogli::Client::OAuthException: (#15) The method you are calling must be called with an app secret signed session
  from ~/gems/ruby-1.9.2-p136/gems/mogli-0.0.28/lib/mogli/client.rb:69:in `raise_error_by_type_and_message'
```

Used [mini_fb](https://github.com/appoxy/mini_fb) and this post as workaround: http://jasonpearl.com/?p=31

How do I a do a app secret signed post with Mogli?

**Comment by flipkick** [comment]
client = Mogli::AppClient.create_and_authenticate_as_application(app_id, secret)
client.post("/app_id/accounts/test-users?installed=true", nil, {})

like this. replace app_id and secret.
