### ISSUE TITLE
Dealing with Mogli::Client::OAuthException

### ISSUE THREAD

**Issue by oscardelben** [mmangino/mogli#52]
How should one deal with Mogli::Client::OAuthException? In particular we sometimes get the following error:

Error validating access token: Session has expired at unix time 1305727200. The current unix time is 1305801471.

Right now we just do the following:

```
session[:access_token] = nil
```

But I wonder if there's a better way to renew the token?

**Comment by mmangino** [comment]
That's what we do too.

Mike

On May 19, 2011, at 6:45 AM, oscardelben wrote:

> How should one deal with Mogli::Client::OAuthException? In particular we sometimes get the following error:
> 
> Error validating access token: Session has expired at unix time 1305727200. The current unix time is 1305801471.
> 
> Right now we just do the following:
> 
>    session[:access_token] = nil
> 
> But I wonder if there's a better way to renew the token?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mmangino/mogli/issues/52

## 

Mike Mangino
http://www.elevatedrails.com

**Comment by khanimdad** [comment]
I have same issue, but above mentioned solution did not work for me, still searching for solution

**Comment by mmangino** [comment]
khanimdad, what do you mean that doesn't work? The auth token has expired, so you need to get a new one. You could also add a filter to check for expired tokens and re-request, or ask for offline access, but this is an app design issue, not a problem with mogli.

**Comment by khanimdad** [comment]
Despite having the offline access permission, i am getting Mogli::Client::OAuthException: Error validating access token: Session has expired at unix time 1309777200. The current unix time is 1309850560. Also some time it does not work smoothly, ie somehow session does not get clearly completely. So if it is a  design issue how could i handle this?

**Comment by mmangino** [comment]
It's hard to tell without seeing your application. The only thing mogli can do with an expired session is to notify you. How you handle that is up to you.

Mike

On Jul 5, 2011, at 7:48 AM, khanimdad wrote:

> Despite having the offline access permission, i am getting Mogli::Client::OAuthException: Error validating access token: Session has expired at unix time 1309777200. The current unix time is 1309850560. Also some time it does not work smoothly, ie somehow session does not get clearly completely. So if it is a  design issue how could i handle this?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mmangino/mogli/issues/52#issuecomment-1503107

## 

Mike Mangino
http://www.elevatedrails.com

**Comment by stevenou** [comment]
I'm trying to catch Mogli::Client:OAuthException application-wide to redirect the user to re-authenticate with Facebook. 

I'm using rescue_from in my ApplicationController. 

BUT, it does't seem to catch it. rescue_from Exception works, but rescue_from Mogli::Client::OAuthException doesn't. Any ideas as to why? It clearly shows Mogli::Client::OAuthException as the exception on the development error page.

**Comment by mmangino** [comment]
This sounds like a rails issue. Is the exception raised in a filter? can you provide a stack trace?

**Comment by jfeng** [comment]
mmangino, I cannot reproduce the problem today, but yes, the exception is raised in a before filter.

**Comment by mmangino** [comment]
Is that the expected behavior? Does rescue_from work in before filters? I don't know if I've ever tried it.

It seems like you need to trace the execution in Rails and figure out why that isn't working.

Mike

On Oct 19, 2011, at 9:29 PM, Jia Feng wrote:

> mmangino, I cannot reproduce the problem today, but yes, the exception is raised in a before filter.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mmangino/mogli/issues/52#issuecomment-2463550

## 

Mike Mangino
http://www.elevatedrails.com

**Comment by stevenou** [comment]
Really weird, but in my case it looks like the Mogli::Client::OAuthException was in turn causing an ActionView::Template::Error, so the rescue_from wouldn't catch Mogli::Client::OAuthException but would catch Exception or ActionView::Template::Error. 

I don't really remember anymore but I think I solved it by moving code that executed Mogli methods out of the view and into the controller.

For example, perhaps I had `<%= @current_user.fb_friends.each do |friend| %>`, where `@current_user.fb_friends` would execute some Mogli code to fetch your friends. In this case the exception would end up causing the ActionView::Template::Error. Instead, I just did `@fb_friends = @current_user.fb_friends` in the controller and used @fb_friends in the view instead.

Try it, I think that's what worked for me.

**Comment by jfeng** [comment]
I use `current_facebook_user.friends` in controller, and use `rescue_from Mogli::Client::OAuthException, :with => :handle_oauth_exception` to catch OAuthException, but a Mogli::Client::HTTPException raised instead of Mogli::Client::OAuthException

**Comment by mmangino** [comment]
and why is the HTTPException raised?

  raise HTTPException if data.respond_to?(:code) and data.code != 200

Can you look at the data there and see what the code and data are? We don't have a success with an Oauth problem, we have an http failure, therefore Mogli is doing what is should in my mind.

**Comment by jfeng** [comment]
The following are the data I get:

```
data.code = 200
#<HTTParty::Response:0x112dddea8 @parsed_response={"error_msg"=>"Error validating access token: The session has been invalidated because the user has changed the password.", "request_args"=>[{"value"=>"fql.query", "key"=>"method"}, {"value"=>"SELECT publish_stream,create_event,rsvp_event,offline_access,publish_checkins,user_about_me,user_activities,user_birthday,user_education_history,user_events,user_groups,user_hometown,user_interests,user_likes,user_location,user_notes,user_online_presence,user_photo_video_tags,user_photos,user_relationships,user_relationship_details,user_religion_politics,user_status,user_videos,user_website,user_work_history,email,read_friendlists,read_insights,read_mailbox,read_requests,read_stream,xmpp_login,ads_management,user_checkins,manage_pages FROM permissions WHERE uid = 1452498470", "key"=>"query"}, {"value"=>"json", "key"=>"format"}, {"value"=>"AAAD5H5Nr4AQBAD6GKKD8hbXlZCCSCjRHhUxgas10jJiI4ozbLW7sUY0hU4kTE4HTrMmlqnjo1ABaGJCKnqHBNr315yS4ZD", "key"=>"access_token"}], "error_code"=>190}, @response=#<Net::HTTPOK 200 OK readbody=true>, @headers={"expires"=>["Thu, 20 Oct 2011 12:20:19 -0700"], "access-control-allow-origin"=>["*"], "content-type"=>["application/json"], "connection"=>["close"], "date"=>["Thu, 20 Oct 2011 19:19:19 GMT"], "content-length"=>["961"], "cache-control"=>["public, max-age=60"], "x-fb-rev"=>["460957"], "x-fb-server"=>["10.54.92.45"], "pragma"=>[""]}>



data.code = 400
#<HTTParty::Response:0x112cb46d0 @parsed_response={"error"=>{"type"=>"OAuthException", "message"=>"Error validating access token: The session has been invalidated because the user has changed the password."}}, @response=#<Net::HTTPBadRequest 400 Bad Request readbody=true>, @headers={"expires"=>["Sat, 01 Jan 2000 00:00:00 GMT"], "access-control-allow-origin"=>["*"], "content-type"=>["text/javascript; charset=UTF-8"], "connection"=>["close"], "www-authenticate"=>["OAuth \"Facebook Platform\" \"invalid_token\" \"Error validating access token: The session has been invalidated because the user has changed the password.\""], "date"=>["Thu, 20 Oct 2011 19:19:20 GMT"], "content-length"=>["154"], "cache-control"=>["no-store"], "x-fb-rev"=>["460957"], "x-fb-server"=>["10.37.14.120"], "pragma"=>["no-cache"]}>
```

It seems that the OAuthException has a code 400, so Mogli supposed to raise a HTTPException in this case?

**Comment by mmangino** [comment]
Okay, so can you send a patch that checks for either 200 or 400 or the request status? That should take care of the issue.

Mike

On Oct 20, 2011, at 3:25 PM, Jia Feng wrote:

> The following are the data I get:
> 
> #<HTTParty::Response:0x112dddea8 @parsed_response={"error_msg"=>"Error validating access token: The session has been invalidated because the user has changed the password.", "request_args"=>[{"value"=>"fql.query", "key"=>"method"}, {"value"=>"SELECT publish_stream,create_event,rsvp_event,offline_access,publish_checkins,user_about_me,user_activities,user_birthday,user_education_history,user_events,user_groups,user_hometown,user_interests,user_likes,user_location,user_notes,user_online_presence,user_photo_video_tags,user_photos,user_relationships,user_relationship_details,user_religion_politics,user_status,user_videos,user_website,user_work_history,email,read_friendlists,read_insights,read_mailbox,read_requests,read_stream,xmpp_login,ads_management,user_checkins,manage_pages FROM permissions WHERE uid = 1452498470", "key"=>"query"}, {"value"=>"json", "key"=>"format"}, {"value"=>"AAAD5H5Nr4AQBAD6GKKD8hbXlZCCSCjRHhUxgas10jJiI4ozbLW7sUY0hU4kTE4HTrMmlqnjo1ABaGJCKnqHBNr315yS4ZD", "k
> ey"=>"access_token"}], "error_code"=>190}, @response=#<Net::HTTPOK 200 OK readbody=true>, @headers={"expires"=>["Thu, 20 Oct 2011 12:20:19 -0700"], "access-control-allow-origin"=>["*"], "content-type"=>["application/json"], "connection"=>["close"], "date"=>["Thu, 20 Oct 2011 19:19:19 GMT"], "content-length"=>["961"], "cache-control"=>["public, max-age=60"], "x-fb-rev"=>["460957"], "x-fb-server"=>["10.54.92.45"], "pragma"=>[""]}>
> 
> #<HTTParty::Response:0x112cb46d0 @parsed_response={"error"=>{"type"=>"OAuthException", "message"=>"Error validating access token: The session has been invalidated because the user has changed the password."}}, @response=#<Net::HTTPBadRequest 400 Bad Request readbody=true>, @headers={"expires"=>["Sat, 01 Jan 2000 00:00:00 GMT"], "access-control-allow-origin"=>["*"], "content-type"=>["text/javascript; charset=UTF-8"], "connection"=>["close"], "www-authenticate"=>["OAuth \"Facebook Platform\" \"invalid_token\" \"Error validating access token: The session has been invalidated because the user has changed the password.\""], "date"=>["Thu, 20 Oct 2011 19:19:20 GMT"], "content-length"=>["154"], "cache-control"=>["no-store"], "x-fb-rev"=>["460957"], "x-fb-server"=>["10.37.14.120"], "pragma"=>["no-cache"]}>
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mmangino/mogli/issues/52#issuecomment-2473186

## 

Mike Mangino
http://www.elevatedrails.com

**Comment by jfeng** [comment]
I pulled a request (https://github.com/mmangino/mogli/pull/89) for this

**Comment by mmangino** [comment]
and I just merged it. Thanks!

Mike

On Oct 20, 2011, at 5:06 PM, Jia Feng wrote:

> I pulled a request (https://github.com/mmangino/mogli/pull/89) for this
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mmangino/mogli/issues/52#issuecomment-2474401

## 

Mike Mangino
http://www.elevatedrails.com
