### ISSUE TITLE
Not finding the username field in Mogli::User

### ISSUE THREAD

**Issue by alexsherstinsky** [mmangino/mogli#54]
Hi, Michael:

Hope all is well.

I was wondering -- maybe I am missing something -- I could not find username in User (only in Page).  Is there a way to get that (optional) field (e.g., my username on Facebook is alex.sherstinsky).  Another thought -- I know you have the methods to get the various image URLs; what about the user's profile URL (e.g., http://www.facebook.com/profile.php?id=706826) such that the access_token would not be required?

Thank you, and Regards.
--Alex

**Comment by mmangino** [comment]
On Jun 1, 2011, at 10:27 AM, alexsherstinsky wrote:

> Hi, Michael:
> 
> Hope all is well.
> 
> I was wondering -- maybe I am missing something -- I could not find username in User (only in Page).  Is there a way to get that (optional) field (e.g., my username on Facebook is alex.sherstinsky).  Another thought -- I know you have the methods to get the various image URLs; what about the user's profile URL (e.g., http://www.facebook.com/profile.php?id= 706826) such that the access_token would not be required?

I'm not sure about username.  Is it available if you define it on user? Is it not defined on a parent class? Are you getting any warnings about the missing field? As far as images go, the profile url has a known URL. You can likely use that. 

Mike

> Thank you, and Regards.
> --Alex
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mmangino/mogli/issues/54

## 

Mike Mangino
http://www.elevatedrails.com

**Comment by alexsherstinsky** [comment]
Hi, Mike:

What I am seeing is that Page has username, but both Page and User -- are siblings -- extend Profile, which does not have username (i.e., username is not defined in Profile, their parent class).  In order to check if there would be a warning, I tried accessing the username field of a Mogli::User, but got an error:
NoMethodError (undefined method `username' for Alex Sherstinsky:Mogli::User)

As far as the profile url having a known URL, do you mean something like http://www.facebook.com/profile.php?id= 706826 or something else?

Thank you,
--Alex

**Comment by mmangino** [comment]
On Jun 1, 2011, at 4:14 PM, alexsherstinsky wrote:

> Hi, Mike:
> 
> What I am seeing is that Page has username, but both Page and User -- are siblings -- extend Profile, which does not have username (i.e., username is not defined in Profile, their parent class).  In order to check if there would be a warning, I tried accessing the username field of a Mogli::User, but got an error:
> NoMethodError (undefined method `username' for Alex Sherstinsky:Mogli::User)
> 
> As far as the profile url having a known URL, do you mean something like http://www.facebook.com/profile.php?id= 706826 or something else?

Profile photos have a known url. Look at the method on user. Also, try adding the username on Mogli::User. If that works, you can move it back to profile and send a pull request.

Mike

> Thank you,
> --Alex
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mmangino/mogli/issues/54#comment_1276853

## 

Mike Mangino
http://www.elevatedrails.com

**Comment by alexsherstinsky** [comment]
Hi, Mike:

I see what you mean regarding the username -- I will do as you said.

Regarding profile, I was looking for the URL for the API to get the user profile page (like http://www.facebook.com/profile.php?id= 706826 or http://www.facebook.com/username -- which is partly why I am interested in having Mogli::User#username), not the image URL (the latter I found through Mogli::Profile).

Thanks,
--Alex

**Comment by mmangino** [comment]
Ah, got it. Hopefully you will be able to easily get the username. I not, you can always use the profile.php url. It will redirect to the actual username. 

Mike

On Jun 1, 2011, at 4:40 PM, alexsherstinsky wrote:

> Hi, Mike:
> 
> I see what you mean regarding the username -- I will do as you said.
> 
> Regarding profile, I was looking for the URL for the API to get the user profile page (like http://www.facebook.com/profile.php?id= 706826 or http://www.facebook.com/username -- which is partly why I am interested in having Mogli::User#username), not the image URL (the latter I found through Mogli::Profile).
> 
> Thanks,
> --Alex
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mmangino/mogli/issues/54#comment_1277008

## 

Mike Mangino
http://www.elevatedrails.com
