### ISSUE TITLE
Get Page Id and other page related information

### ISSUE THREAD

**Issue by nehaverma8** [mmangino/mogli#65]
I need to somehow get the page on which my app is added. My app can be added to several pages and the app content will be customized depending on which page the request came from. 

Can you point me to some documentation /right direction? I have searched a lot but most of the examples are pertaining to Users. I don't need any user information nor do I want to post to any wall. 

Appreciate your help.

**Comment by mmangino** [comment]
Sorry, that's not something I've ever tried to do. I might try asking on the google group.

Mike

On Aug 9, 2011, at 12:39 PM, nehaverma8 wrote:

> I need to somehow get the page on which my app is added. My app can be added to several pages and the app content will be customized depending on which page the request came from. 
> 
> Can you point me to some documentation /right direction? I have searched a lot but most of the examples are pertaining to Users. I don't need any user information nor do I want to post to any wall. 
> 
> Appreciate your help.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mmangino/mogli/issues/65

## 

Mike Mangino
http://www.elevatedrails.com

**Comment by mmangino** [comment]
Now that I've done that, I can give you our approach. We do two things. First, we look at the referrer and parse that to get the page info. Facebook says that the initial request includes the page id in the signed request data, so you may be able to pull it out of the facebook params.
