### ISSUE TITLE
Bug - Invalid Authenticity token

### ISSUE THREAD

**Issue by JaidevSoin** [mmangino/mogli#7]
Currently using User.find raises OAuthException: Invalid OAuth access token

The access token is invalid because in Mogli::Client.create_from_code_and_authenticator the access token is not unescaped. It is passed unescaped to httparty, which escapes it a second time.

The auth token uses a | separator. The first escape escapes that to %7c, which the graph API accepts. The second escape escapes that to %257C. The graph API will accept an access token that has been escaped once, but not one that has been escaped twice. It is likely that the graph api not accepting tokens that have been double escaped is a very recent thing.

Changing the parts loop to hash[k]=CGI.unescape(v) seems to make things work fine in a monkey patch.

Cheers

**Comment by mmangino** [comment]
Thanks for the patch
