### ISSUE TITLE
Can't convert String into Integer (Mogli, lib/mogli/user.rb:113:in `[]')

### ISSUE THREAD

**Issue by ollie** [mmangino/mogli#75]
Hello,

We received this error message and we thought we would let you know about it in case you know what it's about.

<pre>
  can't convert String into Integer
  mogli (0.0.27) lib/mogli/user.rb:113:in `[]'
</pre>

The problem is we have no idea how to reproduce this error, even how it happens - whether it is on our side or your side or Facebook's side. All we can give you is the top part of the backtrace:

<pre>
  mogli (0.0.27) lib/mogli/user.rb:113:in `[]'
  mogli (0.0.27) lib/mogli/user.rb:113:in `fetch_permissions'
  mogli (0.0.27) lib/mogli/user.rb:112:in `each'
  mogli (0.0.27) lib/mogli/user.rb:112:in `fetch_permissions'
  mogli (0.0.27) lib/mogli/user.rb:95:in `has_permission?'
  app/views/games/_finished_game_options.html.erb:32:in `_app_views_games__finished_game_options_html_erb___331147463_40777860_6764748'
  actionpack (3.0.7) lib/action_view/template.rb:135:in `send'
  actionpack (3.0.7) lib/action_view/template.rb:135:in `render'
  ... more Rails backtrace
</pre>

I thought of a possible fix, but I am not sure if it's a really a fix, more like a monkey patch.

<pre>
  ALL_EXTENDED_PERMISSIONS.each do |perm|
    @extended_permissions[perm] = (perms_query_result[perm.to_s] == 1 rescue false) # added rescue false
  end
</pre>

Thank you,
Ollie

**Comment by mmangino** [comment]
Can you try to capture the response from Facebook? that will help us figure out why this is going wrong.

**Comment by ollie** [comment]
Well we don't log the responses so I probably can't. We can probably set it up if you'd like though.

**Comment by mmangino** [comment]
That would be great. It's hard to just guess at what is happening.

Mike

On Sep 29, 2011, at 12:01 PM, Oldřich Vetešník wrote:

> Well we don't log the responses so I probably can't. We can probably set it up if you'd like though.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mmangino/mogli/issues/75#issuecomment-2239261

## 

Mike Mangino
http://www.elevatedrails.com
