### ISSUE TITLE
Revoke authorization

### ISSUE THREAD

**Issue by tobymarsden** [mmangino/mogli#76]
I note that Facebook has (finally) implemented the ability to revoke the app's authorization in the Graph API: http://developers.facebook.com/docs/reference/rest/auth.revokeAuthorization/

Apparently you need to issue an HTTP DELETE request to /PROFILE_ID/permissions. I can't figure out whether implementing this would be as straightforward as introducing a bare-bones Permission model or not. Anyone?

**Comment by mmangino** [comment]
I think it could easily be a method on the profile object. I don't think it needs to be a new model, since there isn't any data associated with it. I'd love to get a patch to add this.
