### ISSUE TITLE
posts on home has no link on from 

### ISSUE THREAD

**Issue by stupied4ever** [mmangino/mogli#87]
@home = @current_user.home

@home.first.from.link is null

not only the first ... all of them are empty.

**Comment by mmangino** [comment]
Is that included in the data from the graph API? I thought the data provided for users was very minimal.

**Comment by stupied4ever** [comment]
@mmangino,

i looked in the graph api and ir returns only the Name and the ID in the From object. But we use the same object, so we should  document it  or we should change the object ? Or we should do nothing ??

**Comment by mmangino** [comment]
I don't plan on documenting the graph API in mogli. If somebody wants to know what data they get from each call, they should look at the graph documentation.

Mike

On Oct 17, 2011, at 10:11 AM, Rafael da Silva Almeida wrote:

> @mmangino,
> 
> i looked in the graph api and ir returns only the Name and the ID in the From object. But we use the same object, so we should  document it  or we should change the object ? Or we should do nothing ??
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mmangino/mogli/issues/87#issuecomment-2429186

## 

Mike Mangino
http://www.elevatedrails.com

**Comment by stupied4ever** [comment]
Ok ok ... thx for the attention.

## []`s

Rafael Almeida
www.rafaelalmeida.net
7265-3019

Antes de imprimir esse e-mail, eu pensei no seu carro gigante parado na
garagem do seu trabalho... se voc pode ter um carro desse tamanho para
andar sozinho, eu posso imprimir o que me der na telha.
