### ISSUE TITLE
proxy support in create_from_code_and_authenticator

### ISSUE THREAD

**Issue by sdabet** [mmangino/mogli#88]
I didn't find any way to provide proxy information when using the following static method : Mogli::Client.create_from_code_and_authenticator()

Is it somehow possible ?

**Comment by mmangino** [comment]
I've never needed to use a proxy. If it isn't possible, I'm happy to take clean patches with tests implementing this functionality.

**Comment by sdabet** [comment]
Ok, I'll let you know if I come up with some nice & clean solution. Thanks for the reply.
