### ISSUE TITLE
Mogli::Client::HTTPException: Mogli::Client::HTTPException

### ISSUE THREAD

**Issue by pragmaticsc** [mmangino/mogli#91]
in console when I do:
client = Mogli::Client.new("<your_access_token>")
=> #<Mogli::Client:0x00000003c30d40 @access_token="AAAEHfyxuRZAwBAEmJZB6IlAf128TiIPK9V2KpJ1YYLvjpEj7yRlVzUZB9jqgsOJMVX5ZAXglv5hSywf0J0lytqW9A9jUHNRQp2Q4iCmElgZDCD", @expiration=2021-11-15 20:14:20 +0000, @default_params={:access_token=>"AAAEHfyxuRZAwBAEmJZB6IlAf128TiIPK9V2KpJ1YYLvjpEj7yRlVzUZB9jqgsOJMVX5ZAXglv5hSywf0J0lytqW9A9jUHNRQp2Q4iCmElgZDCD"}>
myself  = Mogli::User.find("me",client)

I get the HTTPException... I have found no help anywhere for this.

I am on Rails 3.1.1 with Ruby 1.9.2

**Comment by mmangino** [comment]
What http exception?

**Comment by mmangino** [comment]
Without details about the actual exception and the stack trace, this isn't something we can diagnose.
