### ISSUE TITLE
New timeout exceptions when using oauth2, how to handle

### ISSUE THREAD

**Issue by rbjarnason** [mmangino/mogli#95]
Recently switched over to oauth2, now keep on getting quite a bit of those sort of exceptions thrown:
Mogli::Client::OAuthException: Code was invalid or expired. Session has expired at unix time 1323853200. 

What is the recommended way of handling those?

**Comment by mmangino** [comment]
Catch them and re-auth as per the facebook docs

**Comment by rbjarnason** [comment]
Is there a function in Facebooker2 for doing this re-auth or do I need to implement it myself from the Facebook Javascript API?

**Comment by mmangino** [comment]
There isn't. You can either use the mogli authenticator with the redirect or use the JS SDK

Mike
