### ISSUE TITLE
overridden method get_and_map in AppClient

### ISSUE THREAD

**Issue by mperice** [mmangino/mogli#99]
Hi!

In commit #c5341e32fe55a232eb1dc711010d86f172cf5500 added overriding method  get_and_map in AppClient model causes an error when trying to authenticate as an app using the create_and_authenticate_as_application method, for instance when trying to delete an AppRequest:

```
  client = Mogli::Client.create_and_authenticate_as_application(Facebooker2.app_id, Facebooker2.secret)
  app_request = Mogli::AppRequest.find(request_id, client)
  app_request.destroy
```

With the code above I get an OAuthException  'Unknown path components: /23402843..', if I comment out the method in AppClient, it works fine.

**Comment by mmangino** [comment]
Do the tests pass with that code gone? Hopefully the tests provide an explanation for why it exists.

**Comment by mperice** [comment]
Don't know. All I know it was added by travis on July 13, it's probably needed for the TestUser class, which he added, I guess.

**Comment by mmangino** [comment]
Okay, I say remove it and send a pull request. I'll get it added shortly then.

Mike
